
export default class JobModel{
    constructor(id, jobCatagory, jobDesignation, jobLocation, companyName, salary, applyBy, skillRequired, numberOfOpening, jobPosted, logo){
        this.id = id;
        this.jobCatagory = jobCatagory;
        this.jobDesignation = jobDesignation;
        this.jobLocation = jobLocation;
        this.companyName = companyName;
        this.salary = salary;
        this.applyBy = applyBy;
        this.skillRequired = skillRequired;
        this.numberOfOpening = numberOfOpening;
        this.jobPosted = jobPosted;
        this.logo = logo;
        this.applicants = [];
    }
    addNewJob(){

    }
    getAllJobs(){
        console.log(jobs)
        return jobs;
    }
    findJob(id){
        const found = jobs.find(u => u.id == id);
        return found;
    }
    updateJob(){

    }
    addNewApplicant(){

    }
    getAllApplicant(){

    }
    deleteJob(){

    }
}

const jobData = [
  {
    "id": 1,
    "jobCategory": "Software Development",
    "jobDesignation": "Senior Full Stack Engineer",
    "jobLocation": "Remote",
    "companyName": "Tech Innovations Inc.",
    "logo": "https://cdn.worldvectorlogo.com/logos/apple-1.svg",
    "salary": "$120,000 - $160,000",
    "applyBy": "2026-03-15",
    "skillRequired": ["React", "Node.js", "AWS", "MongoDB", "TypeScript"],
    "numberOfOpening": 2,
    "jobPosted": "2026-01-20"
  },
  {
    "id": 2,
    "jobCategory": "Data Science",
    "jobDesignation": "Data Scientist",
    "jobLocation": "San Francisco, CA",
    "companyName": "Data Insights Co.",
    "logo": "https://cdn.worldvectorlogo.com/logos/microsoft-1.svg",
    "salary": "$110,000 - $145,000",
    "applyBy": "2026-03-10",
    "skillRequired": ["Python", "R", "Machine Learning", "SQL", "TensorFlow"],
    "numberOfOpening": 3,
    "jobPosted": "2026-01-25"
  },
  {
    "id": 3,
    "jobCategory": "Marketing",
    "jobDesignation": "Digital Marketing Manager",
    "jobLocation": "New York, NY",
    "companyName": "Global Brands Ltd.",
    "logo": "https://cdn.worldvectorlogo.com/logos/amazon-1.svg",
    "salary": "$80,000 - $100,000",
    "applyBy": "2026-02-28",
    "skillRequired": ["SEO", "SEM", "Content Marketing", "Social Media", "Google Analytics"],
    "numberOfOpening": 1,
    "jobPosted": "2026-01-10"
  },
  {
    "id": 4,
    "jobCategory": "Human Resources",
    "jobDesignation": "HR Business Partner",
    "jobLocation": "London, UK",
    "companyName": "People First Solutions",
    "logo": "https://cdn.worldvectorlogo.com/logos/facebook-1.svg",
    "salary": "£50,000 - £65,000",
    "applyBy": "2026-03-20",
    "skillRequired": ["Recruitment", "Employee Relations", "HRIS", "Performance Management"],
    "numberOfOpening": 1,
    "jobPosted": "2026-01-18"
  },
  {
    "id": 5,
    "jobCategory": "Design",
    "jobDesignation": "UX/UI Designer",
    "jobLocation": "Remote",
    "companyName": "Creative Minds Studio",
    "logo": "https://cdn.worldvectorlogo.com/logos/twitter-1.svg",
    "salary": "$90,000 - $115,000",
    "applyBy": "2026-03-05",
    "skillRequired": ["Figma", "Sketch", "User Research", "Prototyping", "Adobe XD"],
    "numberOfOpening": 2,
    "jobPosted": "2026-01-30"
  },
  {
    "id": 6,
    "jobCategory": "Sales",
    "jobDesignation": "Account Executive",
    "jobLocation": "Chicago, IL",
    "companyName": "SalesForce Pro",
    "logo": "https://cdn.worldvectorlogo.com/logos/linkedin-1.svg",
    "salary": "$70,000 - $90,000 + Commission",
    "applyBy": "2026-03-25",
    "skillRequired": ["CRM", "Lead Generation", "Negotiation", "Sales Strategy"],
    "numberOfOpening": 4,
    "jobPosted": "2026-01-15"
  },
  {
    "id": 7,
    "jobCategory": "Software Development",
    "jobDesignation": "Junior Frontend Developer",
    "jobLocation": "Austin, TX",
    "companyName": "Web Solutions LLC",
    "logo": "https://cdn.worldvectorlogo.com/logos/github-1.svg",
    "salary": "$60,000 - $80,000",
    "applyBy": "2026-03-01",
    "skillRequired": ["HTML", "CSS", "JavaScript", "React"],
    "numberOfOpening": 3,
    "jobPosted": "2026-01-22"
  },
  {
    "id": 8,
    "jobCategory": "IT Operations",
    "jobDesignation": "DevOps Engineer",
    "jobLocation": "Seattle, WA",
    "companyName": "CloudOps Inc.",
    "logo": "https://cdn.worldvectorlogo.com/logos/docker-1.svg",
    "salary": "$100,000 - $130,000",
    "applyBy": "2026-03-18",
    "skillRequired": ["Docker", "Kubernetes", "CI/CD", "Ansible", "AWS"],
    "numberOfOpening": 2,
    "jobPosted": "2026-01-28"
  },
  {
    "id": 9,
    "jobCategory": "Finance",
    "jobDesignation": "Financial Analyst",
    "jobLocation": "Boston, MA",
    "companyName": "Capital Growth Partners",
    "logo": "https://cdn.worldvectorlogo.com/logos/stripe-1.svg",
    "salary": "$75,000 - $95,000",
    "applyBy": "2026-03-08",
    "skillRequired": ["Financial Modeling", "Excel", "Data Analysis", "GAAP"],
    "numberOfOpening": 1,
    "jobPosted": "2026-01-12"
  },
  {
    "id": 10,
    "jobCategory": "Healthcare",
    "jobDesignation": "Registered Nurse",
    "jobLocation": "Los Angeles, CA",
    "companyName": "City General Hospital",
    "logo": "https://cdn.worldvectorlogo.com/logos/red-cross-1.svg",
    "salary": "$85,000 - $105,000",
    "applyBy": "2026-03-30",
    "skillRequired": ["Patient Care", "BLS", "ACLS", "Electronic Health Records"],
    "numberOfOpening": 5,
    "jobPosted": "2026-01-05"
  },
  {
    "id": 11,
    "jobCategory": "Education",
    "jobDesignation": "High School Math Teacher",
    "jobLocation": "Denver, CO",
    "companyName": "Mountain View High School",
    "logo": "https://cdn.worldvectorlogo.com/logos/harvard-university.svg",
    "salary": "$55,000 - $70,000",
    "applyBy": "2026-04-01",
    "skillRequired": ["Curriculum Development", "Classroom Management", "Algebra", "Calculus"],
    "numberOfOpening": 2,
    "jobPosted": "2026-01-01"
  },
  {
    "id": 12,
    "jobCategory": "Customer Service",
    "jobDesignation": "Customer Support Specialist",
    "jobLocation": "Remote",
    "companyName": "HelpDesk Solutions",
    "logo": "https://cdn.worldvectorlogo.com/logos/zendesk-1.svg",
    "salary": "$40,000 - $50,000",
    "applyBy": "2026-02-20",
    "skillRequired": ["Communication", "Problem-solving", "CRM Software", "Technical Support"],
    "numberOfOpening": 10,
    "jobPosted": "2026-01-10"
  },
  {
    "id": 13,
    "jobCategory": "Software Development",
    "jobDesignation": "Backend Engineer (Python)",
    "jobLocation": "Dublin, Ireland",
    "companyName": "Global Tech Solutions",
    "logo": "https://cdn.worldvectorlogo.com/logos/python-1.svg",
    "salary": "€60,000 - €80,000",
    "applyBy": "2026-03-22",
    "skillRequired": ["Python", "Django", "REST APIs", "PostgreSQL", "Docker"],
    "numberOfOpening": 2,
    "jobPosted": "2026-01-29"
  },
  {
    "id": 14,
    "jobCategory": "Data Science",
    "jobDesignation": "Machine Learning Engineer",
    "jobLocation": "Bengaluru, India",
    "companyName": "AI Innovations Pvt. Ltd.",
    "logo": "https://cdn.worldvectorlogo.com/logos/nvidia-1.svg",
    "salary": "₹1,500,000 - ₹2,500,000",
    "applyBy": "2026-03-17",
    "skillRequired": ["Python", "TensorFlow", "PyTorch", "NLP", "Computer Vision"],
    "numberOfOpening": 3,
    "jobPosted": "2026-01-24"
  },
  {
    "id": 15,
    "jobCategory": "Marketing",
    "jobDesignation": "Content Strategist",
    "jobLocation": "Remote",
    "companyName": "Storytellers Agency",
    "logo": "https://cdn.worldvectorlogo.com/logos/medium-1.svg",
    "salary": "$70,000 - $90,000",
    "applyBy": "2026-03-03",
    "skillRequired": ["Content Creation", "SEO", "Copywriting", "Brand Strategy"],
    "numberOfOpening": 1,
    "jobPosted": "2026-01-11"
  },
  {
    "id": 16,
    "jobCategory": "Human Resources",
    "jobDesignation": "Talent Acquisition Specialist",
    "jobLocation": "Sydney, Australia",
    "companyName": "Talent Connect",
    "logo": "https://cdn.worldvectorlogo.com/logos/indeed-1.svg",
    "salary": "AUD 70,000 - AUD 90,000",
    "applyBy": "2026-03-28",
    "skillRequired": ["Recruitment", "Applicant Tracking Systems", "Interviewing"],
    "numberOfOpening": 2,
    "jobPosted": "2026-01-19"
  },
  {
    "id": 17,
    "jobCategory": "Design",
    "jobDesignation": "Graphic Designer",
    "jobLocation": "Toronto, Canada",
    "companyName": "Visual Impact Co.",
    "logo": "https://cdn.worldvectorlogo.com/logos/adobe-illustrator-cc.svg",
    "salary": "CAD 55,000 - CAD 70,000",
    "applyBy": "2026-03-12",
    "skillRequired": ["Adobe Creative Suite", "Branding", "Typography", "Print Design"],
    "numberOfOpening": 1,
    "jobPosted": "2026-01-26"
  },
  {
    "id": 18,
    "jobCategory": "Sales",
    "jobDesignation": "Inside Sales Representative",
    "jobLocation": "Dallas, TX", 
    "companyName": "Growth Solutions Inc.", 
    "logo": "https://cdn.worldvectorlogo.com/logos/google-messages.svg",
    "salary": "$50,000 - $65,000 + Commission",
    "applyBy": "2026-03-07",
    "skillRequired": ["Cold Calling", "Sales Presentations", "CRM"],
    "numberOfOpening": 5,
    "jobPosted": "2026-01-14"
  },
  {
    "id": 19,
    "jobCategory": "Software Development",
    "jobDesignation": "Mobile App Developer (iOS)",
    "jobLocation": "San Jose, CA",
    "companyName": "AppGenius Labs",
    "logo": "https://cdn.worldvectorlogo.com/logos/apple-app-store.svg",
    "salary": "$110,000 - $150,000",
    "applyBy": "2026-03-29",
    "skillRequired": ["Swift", "Xcode", "iOS SDK", "RESTful APIs"],
    "numberOfOpening": 2,
    "jobPosted": "2026-01-21"
  },
  {
    "id": 20,
    "jobCategory": "Data Science",
    "jobDesignation": "Data Engineer",
    "jobLocation": "Remote",
    "companyName": "DataFlow Systems",
    "logo": "https://cdn.worldvectorlogo.com/logos/apache-spark.svg",
    "salary": "$105,000 - $135,000",
    "applyBy": "2026-03-14",
    "skillRequired": ["Python", "SQL", "Spark", "ETL", "Cloud Platforms"],
    "numberOfOpening": 2,
    "jobPosted": "2026-01-27"
  },
  {
    "id": 21,
    "jobCategory": "Marketing",
    "jobDesignation": "Product Marketing Manager",
    "jobLocation": "San Francisco, CA",
    "companyName": "Innovate Products Inc.",
    "logo": "https://cdn.worldvectorlogo.com/logos/product-hunt.svg",
    "salary": "$95,000 - $120,000",
    "applyBy": "2026-03-06",
    "skillRequired": ["Product Launch", "Market Research", "Go-to-Market Strategy"],
    "numberOfOpening": 1,
    "jobPosted": "2026-01-13"
  }
];

const jobs = jobData.map(job => new JobModel(
  job.id,
  job.jobCategory,
  job.jobDesignation,
  job.jobLocation,
  job.companyName,
  job.salary,
  job.applyBy,
  job.skillRequired,
  job.numberOfOpening,
  job.jobPosted,
  job.logo
));
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef20",
//     "jobCategory": "IT Operations",
//     "jobDesignation": "Network Administrator",
//     "jobLocation": "Houston, TX",
//     "companyName": "SecureNet Solutions",
//     "salary": "$65,000 - $85,000",
//     "applyBy": "2026-03-23",
//     "skillRequired": ["Cisco", "Networking Protocols", "Firewalls", "Troubleshooting"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-08"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef21",
//     "jobCategory": "Finance",
//     "jobDesignation": "Accountant",
//     "jobLocation": "Miami, FL",
//     "companyName": "Financial Services Group",
//     "salary": "$60,000 - $75,000",
//     "applyBy": "2026-03-09",
//     "skillRequired": ["Bookkeeping", "Tax Preparation", "QuickBooks", "Financial Reporting"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-04"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef22",
//     "jobCategory": "Healthcare",
//     "jobDesignation": "Medical Assistant",
//     "jobLocation": "Phoenix, AZ",
//     "companyName": "Desert Health Clinic",
//     "salary": "$35,000 - $45,000",
//     "applyBy": "2026-03-16",
//     "skillRequired": ["Patient Intake", "Vital Signs", "Medical Terminology", "EMR"],
//     "numberOfOpening": 3,
//     "jobPosted": "2026-01-07"
//   },
//   {
//     "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef23",
//     "jobCategory": "Education",
//     "jobDesignation": "Elementary School Teacher",
//     "jobLocation": "Orlando, FL",
//     "companyName": "Sunshine Elementary",
//     "salary": "$48,000 - $60,000",
//     "applyBy": "2026-04-05",
//     "skillRequired": ["Early Childhood Education", "Lesson Planning", "Classroom Management"],
//     "numberOfOpening": 4,
//     "jobPosted": "2026-01-02"
//   },
//   {
//     "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef24",
//     "jobCategory": "Customer Service",
//     "jobDesignation": "Technical Support Engineer",
//     "jobLocation": "Remote",
//     "companyName": "Global Tech Support",
//     "salary": "$55,000 - $70,000",
//     "applyBy": "2026-03-02",
//     "skillRequired": ["Troubleshooting", "Networking", "Software Support", "Communication"],
//     "numberOfOpening": 5,
//     "jobPosted": "2026-01-09"
//   },
//   {
//     "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef25",
//     "jobCategory": "Software Development",
//     "jobDesignation": "QA Engineer",
//     "jobLocation": "Bengaluru, India",
//     "companyName": "Quality Assured Software",
//     "salary": "₹800,000 - ₹1,200,000",
//     "applyBy": "2026-03-19",
//     "skillRequired": ["Manual Testing", "Automation Testing", "Selenium", "JIRA"],
//     "numberOfOpening": 3,
//     "jobPosted": "2026-01-23"
//   },
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef26",
//     "jobCategory": "Data Science",
//     "jobDesignation": "Business Intelligence Analyst",
//     "jobLocation": "London, UK",
//     "companyName": "Insight Analytics",
//     "salary": "£45,000 - £60,000",
//     "applyBy": "2026-03-11",
//     "skillRequired": ["SQL", "Tableau", "Power BI", "Data Warehousing"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-26"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef27",
//     "jobCategory": "Marketing",
//     "jobDesignation": "Social Media Specialist",
//     "jobLocation": "Remote",
//     "companyName": "Digital Growth Agency",
//     "salary": "$50,000 - $65,000",
//     "applyBy": "2026-02-25",
//     "skillRequired": ["Social Media Management", "Content Creation", "Analytics", "Community Engagement"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-05"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef28",
//     "jobCategory": "Human Resources",
//     "jobDesignation": "HR Generalist",
//     "jobLocation": "Chicago, IL",
//     "companyName": "Corporate Solutions Group",
//     "salary": "$60,000 - $75,000",
//     "applyBy": "2026-03-27",
//     "skillRequired": ["HR Policies", "Payroll", "Benefits Administration", "Compliance"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-16"
//   },
//   {
//     "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef29",
//     "jobCategory": "Design",
//     "jobDesignation": "Product Designer",
//     "jobLocation": "San Francisco, CA",
//     "companyName": "NextGen Products",
//     "salary": "$100,000 - $130,000",
//     "applyBy": "2026-03-04",
//     "skillRequired": ["UX Design", "UI Design", "Figma", "Design Systems", "User Testing"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-29"
//   },
//   {
//     "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef30",
//     "jobCategory": "Sales",
//     "jobDesignation": "Sales Manager",
//     "jobLocation": "New York, NY",
//     "companyName": "Enterprise Sales Corp.",
//     "salary": "$90,000 - $120,000 + Bonus",
//     "applyBy": "2026-03-26",
//     "skillRequired": ["Sales Leadership", "Team Management", "CRM", "Strategic Planning"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-17"
//   },
//   {
//     "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef31",
//     "jobCategory": "Software Development",
//     "jobDesignation": "Cloud Engineer",
//     "jobLocation": "Remote",
//     "companyName": "CloudVerse Technologies",
//     "salary": "$115,000 - $155,000",
//     "applyBy": "2026-03-21",
//     "skillRequired": ["AWS", "Azure", "GCP", "Terraform", "Kubernetes"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-28"
//   },
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef32",
//     "jobCategory": "Data Science",
//     "jobDesignation": "Quantitative Analyst",
//     "jobLocation": "London, UK",
//     "companyName": "Quant Finance Solutions",
//     "salary": "£70,000 - £100,000",
//     "applyBy": "2026-03-13",
//     "skillRequired": ["Quantitative Analysis", "Financial Modeling", "Python", "C++"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-20"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef33",
//     "jobCategory": "Marketing",
//     "jobDesignation": "SEO Specialist",
//     "jobLocation": "Remote",
//     "companyName": "RankUp Digital",
//     "salary": "$55,000 - $70,000",
//     "applyBy": "2026-02-27",
//     "skillRequired": ["SEO Audit", "Keyword Research", "Link Building", "Google Analytics"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-08"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef34",
//     "jobCategory": "Human Resources",
//     "jobDesignation": "Recruitment Coordinator",
//     "jobLocation": "Toronto, Canada",
//     "companyName": "Hiring Hub",
//     "salary": "CAD 45,000 - CAD 55,000",
//     "applyBy": "2026-03-24",
//     "skillRequired": ["Candidate Sourcing", "Interview Scheduling", "ATS Management"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-15"
//   },
//   {
//     "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef35",
//     "jobCategory": "Design",
//     "jobDesignation": "Motion Graphics Designer",
//     "jobLocation": "Los Angeles, CA",
//     "companyName": "Dynamic Visuals Studio",
//     "salary": "$70,000 - $90,000",
//     "applyBy": "2026-03-07",
//     "skillRequired": ["After Effects", "Cinema 4D", "Video Editing", "Storyboarding"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-31"
//   },
//   {
//     "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef36",
//     "jobCategory": "Sales",
//     "jobDesignation": "Business Development Representative",
//     "jobLocation": "Boston, MA",
//     "companyName": "Market Expansion Group",
//     "salary": "$45,000 - $60,000 + OTE",
//     "applyBy": "2026-03-01",
//     "skillRequired": ["Prospecting", "Lead Qualification", "CRM", "Communication"],
//     "numberOfOpening": 4,
//     "jobPosted": "2026-01-10"
//   },
//   {
//     "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef37",
//     "jobCategory": "Software Development",
//     "jobDesignation": "Embedded Software Engineer",
//     "jobLocation": "Munich, Germany",
//     "companyName": "Automotive Tech GmbH",
//     "salary": "€65,000 - €90,000",
//     "applyBy": "2026-03-28",
//     "skillRequired": ["C/C++", "RTOS", "Microcontrollers", "Embedded Linux"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-25"
//   },
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef38",
//     "jobCategory": "Data Science",
//     "jobDesignation": "Data Analyst",
//     "jobLocation": "Remote",
//     "companyName": "Analytics Hub",
//     "salary": "$70,000 - $90,000",
//     "applyBy": "2026-03-09",
//     "skillRequired": ["SQL", "Excel", "Python (Pandas)", "Data Visualization"],
//     "numberOfOpening": 3,
//     "jobPosted": "2026-01-18"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef39",
//     "jobCategory": "Marketing",
//     "jobDesignation": "PPC Specialist",
//     "jobLocation": "Sydney, Australia",
//     "companyName": "AdVantage Marketing",
//     "salary": "AUD 60,000 - AUD 80,000",
//     "applyBy": "2026-03-01",
//     "skillRequired": ["Google Ads", "Bing Ads", "Campaign Optimization", "Analytics"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-06"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef40",
//     "jobCategory": "IT Operations",
//     "jobDesignation": "System Administrator",
//     "jobLocation": "Denver, CO",
//     "companyName": "Enterprise IT Solutions",
//     "salary": "$70,000 - $90,000",
//     "applyBy": "2026-03-20",
//     "skillRequired": ["Linux", "Windows Server", "Virtualization", "Scripting (Bash/PowerShell)"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-12"
//   },
//   {
//     "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef41",
//     "jobCategory": "Finance",
//     "jobDesignation": "Audit Associate",
//     "jobLocation": "New York, NY",
//     "companyName": "Global Audit Firm",
//     "salary": "$60,000 - $75,000",
//     "applyBy": "2026-03-10",
//     "skillRequired": ["Auditing Principles", "GAAP", "Excel", "Analytical Skills"],
//     "numberOfOpening": 3,
//     "jobPosted": "2026-01-03"
//   },
//   {
//     "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef42",
//     "jobCategory": "Healthcare",
//     "jobDesignation": "Physical Therapist",
//     "jobLocation": "San Diego, CA",
//     "companyName": "Coastal Rehab Center",
//     "salary": "$90,000 - $110,000",
//     "applyBy": "2026-03-25",
//     "skillRequired": ["Patient Assessment", "Treatment Planning", "Rehabilitation"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-09"
//   },
//   {
//     "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef43",
//     "jobCategory": "Education",
//     "jobDesignation": "University Lecturer (Computer Science)",
//     "jobLocation": "London, UK",
//     "companyName": "London Metropolitan University",
//     "salary": "£40,000 - £55,000",
//     "applyBy": "2026-04-10",
//     "skillRequired": ["PhD in CS", "Teaching Experience", "Research", "Programming"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-04"
//   },
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef44",
//     "jobCategory": "Customer Service",
//     "jobDesignation": "Bilingual Customer Service Rep",
//     "jobLocation": "Remote",
//     "companyName": "Global Connect Support",
//     "salary": "$42,000 - $52,000",
//     "applyBy": "2026-02-29",
//     "skillRequired": ["Spanish Fluency", "Communication", "Problem-solving"],
//     "numberOfOpening": 6,
//     "jobPosted": "2026-01-11"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef45",
//     "jobCategory": "Software Development",
//     "jobDesignation": "Game Developer (Unity)",
//     "jobLocation": "Vancouver, Canada",
//     "companyName": "PixelPlay Games",
//     "salary": "CAD 70,000 - CAD 95,000",
//     "applyBy": "2026-03-15",
//     "skillRequired": ["Unity3D", "C#", "Game Design", "Shader Development"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-22"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef46",
//     "jobCategory": "Data Science",
//     "jobDesignation": "AI Research Scientist",
//     "jobLocation": "Cambridge, MA",
//     "companyName": "Cognitive AI Labs",
//     "salary": "$130,000 - $180,000",
//     "applyBy": "2026-03-20",
//     "skillRequired": ["Deep Learning", "NLP", "Python", "PyTorch", "Research Publications"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-27"
//   },
//   {
//     "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef47",
//     "jobCategory": "Marketing",
//     "jobDesignation": "Email Marketing Specialist",
//     "jobLocation": "Remote",
//     "companyName": "Engage Campaigns",
//     "salary": "$60,000 - $75,000",
//     "applyBy": "2026-03-05",
//     "skillRequired": ["Email Automation", "Mailchimp", "A/B Testing", "Copywriting"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-14"
//   },
//   {
//     "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef48",
//     "jobCategory": "Human Resources",
//     "jobDesignation": "Compensation & Benefits Analyst",
//     "jobLocation": "Dallas, TX",
//     "companyName": "CompSolutions Inc.",
//     "salary": "$75,000 - $95,000",
//     "applyBy": "2026-03-29",
//     "skillRequired": ["Compensation Structures", "Benefits Administration", "HR Analytics"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-17"
//   },
//   {
//     "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef49",
//     "jobCategory": "Design",
//     "jobDesignation": "Industrial Designer",
//     "jobLocation": "Detroit, MI",
//     "companyName": "Product Form Innovations",
//     "salary": "$80,000 - $100,000",
//     "applyBy": "2026-03-10",
//     "skillRequired": ["SolidWorks", "Rhino", "Prototyping", "Ergonomics"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-02-01"
//   },
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef50",
//     "jobCategory": "Sales",
//     "jobDesignation": "Field Sales Representative",
//     "jobLocation": "Atlanta, GA",
//     "companyName": "Regional Sales Partners",
//     "salary": "$60,000 - $80,000 + Commission",
//     "applyBy": "2026-03-03",
//     "skillRequired": ["Client Relationship Management", "Territory Management", "Presentation Skills"],
//     "numberOfOpening": 3,
//     "jobPosted": "2026-01-12"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef51",
//     "jobCategory": "Software Development",
//     "jobDesignation": "DevOps Engineer (Azure)",
//     "jobLocation": "Remote",
//     "companyName": "Azure Cloud Solutions",
//     "salary": "$100,000 - $130,000",
//     "applyBy": "2026-03-25",
//     "skillRequired": ["Azure DevOps", "Terraform", "PowerShell", "CI/CD"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-30"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef52",
//     "jobCategory": "Data Science",
//     "jobDesignation": "Bioinformatics Scientist",
//     "jobLocation": "Boston, MA",
//     "companyName": "Genomics Research Institute",
//     "salary": "$110,000 - $140,000",
//     "applyBy": "2026-03-18",
//     "skillRequired": ["Python", "R", "Genomics", "Statistical Analysis", "Bioinformatics Tools"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-23"
//   },
//   {
//     "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef53",
//     "jobCategory": "Marketing",
//     "jobDesignation": "Marketing Coordinator",
//     "jobLocation": "Philadelphia, PA",
//     "companyName": "Brand Builders Agency",
//     "salary": "$45,000 - $55,000",
//     "applyBy": "2026-03-08",
//     "skillRequired": ["Marketing Campaigns", "Social Media", "Event Planning", "CRM"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-15"
//   },
//   {
//     "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef54",
//     "jobCategory": "IT Operations",
//     "jobDesignation": "Cybersecurity Analyst",
//     "jobLocation": "Washington D.C.",
//     "companyName": "SecureGuard Solutions",
//     "salary": "$90,000 - $120,000",
//     "applyBy": "2026-03-22",
//     "skillRequired": ["SIEM", "Incident Response", "Network Security", "Vulnerability Assessment"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-10"
//   },
//   {
//     "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef55",
//     "jobCategory": "Finance",
//     "jobDesignation": "Investment Banking Analyst",
//     "jobLocation": "New York, NY",
//     "companyName": "Global Capital Markets",
//     "salary": "$100,000 - $150,000 + Bonus",
//     "applyBy": "2026-03-12",
//     "skillRequired": ["Financial Modeling", "Valuation", "M&A", "Excel"],
//     "numberOfOpening": 4,
//     "jobPosted": "2026-01-05"
//   },
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef56",
//     "jobCategory": "Healthcare",
//     "jobDesignation": "Pharmacist",
//     "jobLocation": "Houston, TX",
//     "companyName": "Community Pharmacy",
//     "salary": "$110,000 - $130,000",
//     "applyBy": "2026-03-31",
//     "skillRequired": ["Medication Dispensing", "Patient Counseling", "Pharmacy Law"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-06"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef57",
//     "jobCategory": "Education",
//     "jobDesignation": "Special Education Teacher",
//     "jobLocation": "Chicago, IL",
//     "companyName": "Inclusive Learning Academy",
//     "salary": "$58,000 - $72,000",
//     "applyBy": "2026-04-08",
//     "skillRequired": ["IEP Development", "Differentiated Instruction", "Behavior Management"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-03"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef58",
//     "jobCategory": "Customer Service",
//     "jobDesignation": "Call Center Agent",
//     "jobLocation": "Remote",
//     "companyName": "Connect Solutions",
//     "salary": "$38,000 - $48,000",
//     "applyBy": "2026-02-22",
//     "skillRequired": ["Active Listening", "Customer Relationship Management", "Data Entry"],
//     "numberOfOpening": 8,
//     "jobPosted": "2026-01-07"
//   },
//   {
//     "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef59",
//     "jobCategory": "Software Development",
//     "jobDesignation": "Android Developer",
//     "jobLocation": "Berlin, Germany",
//     "companyName": "Mobile Innovations GmbH",
//     "salary": "€55,000 - €75,000",
//     "applyBy": "2026-03-20",
//     "skillRequired": ["Kotlin", "Java", "Android SDK", "RESTful APIs", "Material Design"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-26"
//   },
//   {
//     "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef60",
//     "jobCategory": "Data Science",
//     "jobDesignation": "Data Visualization Specialist",
//     "jobLocation": "Remote",
//     "companyName": "Vizualize Data",
//     "salary": "$85,000 - $105,000",
//     "applyBy": "2026-03-16",
//     "skillRequired": ["Tableau", "D3.js", "Power BI", "UI/UX Principles"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-21"
//   },
//   {
//     "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef61",
//     "jobCategory": "Marketing",
//     "jobDesignation": "Brand Manager",
//     "jobLocation": "London, UK",
//     "companyName": "Premium Brands Group",
//     "salary": "£60,000 - £80,000",
//     "applyBy": "2026-03-02",
//     "skillRequired": ["Brand Strategy", "Market Research", "Campaign Management", "Product Launch"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-10"
//   },
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef62",
//     "jobCategory": "Human Resources",
//     "jobDesignation": "Learning & Development Specialist",
//     "jobLocation": "Remote",
//     "companyName": "SkillUp Academy",
//     "salary": "$65,000 - $80,000",
//     "applyBy": "2026-03-26",
//     "skillRequired": ["Instructional Design", "Training Delivery", "LMS Administration", "E-learning"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-18"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef63",
//     "jobCategory": "Design",
//     "jobDesignation": "Architectural Designer",
//     "jobLocation": "New York, NY",
//     "companyName": "Urban Design Collective",
//     "salary": "$75,000 - $95,000",
//     "applyBy": "2026-03-11",
//     "skillRequired": ["AutoCAD", "Revit", "SketchUp", "Building Codes", "Rendering"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-02-02"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef64",
//     "jobCategory": "Sales",
//     "jobDesignation": "Sales Engineer",
//     "jobLocation": "San Francisco, CA",
//     "companyName": "Tech Solutions Inc.",
//     "salary": "$100,000 - $140,000 + Commission",
//     "applyBy": "2026-03-06",
//     "skillRequired": ["Technical Sales", "Product Demonstrations", "Solution Architecture", "CRM"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-13"
//   },
//   {
//     "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef65",
//     "jobCategory": "Software Development",
//     "jobDesignation": "Site Reliability Engineer (SRE)",
//     "jobLocation": "Seattle, WA",
//     "companyName": "Reliable Systems Corp.",
//     "salary": "$120,000 - $160,000",
//     "applyBy": "2026-03-28",
//     "skillRequired": ["Linux", "Python", "Go", "Monitoring (Prometheus)", "Distributed Systems"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-29"
//   },
//   {
//     "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef66",
//     "jobCategory": "Data Science",
//     "jobDesignation": "Machine Learning Researcher",
//     "jobLocation": "Paris, France",
//     "companyName": "AI Research Institute",
//     "salary": "€70,000 - €100,000",
//     "applyBy": "2026-03-21",
//     "skillRequired": ["Deep Learning", "Reinforcement Learning", "Python", "Academic Publications"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-24"
//   },
//   {
//     "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef67",
//     "jobCategory": "Marketing",
//     "jobDesignation": "Growth Hacker",
//     "jobLocation": "Remote",
//     "companyName": "Rapid Growth Marketing",
//     "salary": "$80,000 - $100,000",
//     "applyBy": "2026-03-04",
//     "skillRequired": ["A/B Testing", "Conversion Rate Optimization", "Analytics", "Experimentation"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-11"
//   },
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef68",
//     "jobCategory": "IT Operations",
//     "jobDesignation": "Cloud Security Engineer",
//     "jobLocation": "Remote",
//     "companyName": "CloudSecure Solutions",
//     "salary": "$110,000 - $140,000",
//     "applyBy": "2026-03-27",
//     "skillRequired": ["Cloud Security (AWS/Azure/GCP)", "Compliance", "Penetration Testing", "Scripting"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-16"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef69",
//     "jobCategory": "Finance",
//     "jobDesignation": "Financial Advisor",
//     "jobLocation": "Miami, FL",
//     "companyName": "Wealth Management Group",
//     "salary": "$70,000 - $100,000 + Commission",
//     "applyBy": "2026-03-15",
//     "skillRequired": ["Financial Planning", "Investment Strategies", "Client Relations", "Series 7/66"],
//     "numberOfOpening": 3,
//     "jobPosted": "2026-01-08"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef70",
//     "jobCategory": "Healthcare",
//     "jobDesignation": "Medical Coder",
//     "jobLocation": "Remote",
//     "companyName": "HealthCode Services",
//     "salary": "$45,000 - $60,000",
//     "applyBy": "2026-03-24",
//     "skillRequired": ["ICD-10", "CPT", "Medical Billing", "HIPAA Compliance"],
//     "numberOfOpening": 4,
//     "jobPosted": "2026-01-07"
//   },
//   {
//     "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef71",
//     "jobCategory": "Education",
//     "jobDesignation": "Curriculum Developer",
//     "jobLocation": "Remote",
//     "companyName": "EduTech Solutions",
//     "salary": "$60,000 - $75,000",
//     "applyBy": "2026-04-12",
//     "skillRequired": ["Instructional Design", "E-learning Development", "Subject Matter Expertise"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-05"
//   },
//   {
//     "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef72",
//     "jobCategory": "Customer Service",
//     "jobDesignation": "Customer Success Manager",
//     "jobLocation": "Austin, TX",
//     "companyName": "ClientGrowth Partners",
//     "salary": "$70,000 - $90,000",
//     "applyBy": "2026-03-09",
//     "skillRequired": ["Account Management", "Client Retention", "CRM", "Communication"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-14"
//   },
//   {
//     "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef73",
//     "jobCategory": "Software Development",
//     "jobDesignation": "Staff Software Engineer",
//     "jobLocation": "San Francisco, CA",
//     "companyName": "MegaCorp Tech",
//     "salary": "$180,000 - $250,000",
//     "applyBy": "2026-03-30",
//     "skillRequired": ["System Design", "Distributed Systems", "Mentorship", "Leadership"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-25"
//   },
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef74",
//     "jobCategory": "Data Science",
//     "jobDesignation": "Applied Scientist",
//     "jobLocation": "Seattle, WA",
//     "companyName": "Amazon",
//     "salary": "$150,000 - $200,000",
//     "applyBy": "2026-03-23",
//     "skillRequired": ["Machine Learning", "Experimentation", "Statistical Modeling", "Python", "Java"],
//     "numberOfOpening": 3,
//     "jobPosted": "2026-01-28"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef75",
//     "jobCategory": "Marketing",
//     "jobDesignation": "Performance Marketing Manager",
//     "jobLocation": "Remote",
//     "companyName": "Conversion Kings",
//     "salary": "$90,000 - $110,000",
//     "applyBy": "2026-03-07",
//     "skillRequired": ["Paid Social", "Google Ads", "Analytics", "Budget Management"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-16"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef76",
//     "jobCategory": "Human Resources",
//     "jobDesignation": "HR Coordinator",
//     "jobLocation": "New York, NY",
//     "companyName": "Dynamic Workforce Solutions",
//     "salary": "$48,000 - $60,000",
//     "applyBy": "2026-03-29",
//     "skillRequired": ["Administrative Support", "Onboarding", "HRIS Data Entry", "Communication"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-19"
//   },
//   {
//     "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef77",
//     "jobCategory": "Design",
//     "jobDesignation": "UI Designer",
//     "jobLocation": "Remote",
//     "companyName": "Interface Masters",
//     "salary": "$85,000 - $105,000",
//     "applyBy": "2026-03-14",
//     "skillRequired": ["Figma", "Sketch", "Adobe XD", "Design Systems", "Interaction Design"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-02-03"
//   },
//   {
//     "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef78",
//     "jobCategory": "Sales",
//     "jobDesignation": "Enterprise Account Manager",
//     "jobLocation": "Chicago, IL",
//     "companyName": "Global Enterprise Solutions",
//     "salary": "$110,000 - $150,000 + OTE",
//     "applyBy": "2026-03-08",
//     "skillRequired": ["Enterprise Sales", "Strategic Partnerships", "Negotiation", "CRM"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-17"
//   },
//   {
//     "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef79",
//     "jobCategory": "Software Development",
//     "jobDesignation": "Principal Engineer",
//     "jobLocation": "London, UK",
//     "companyName": "Innovate Systems PLC",
//     "salary": "£90,000 - £130,000",
//     "applyBy": "2026-03-26",
//     "skillRequired": ["Technical Leadership", "Architecture", "Mentoring", "Cloud Native"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-30"
//   },
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef80",
//     "jobCategory": "Data Science",
//     "jobDesignation": "Senior Data Engineer",
//     "jobLocation": "Bengaluru, India",
//     "companyName": "DataStream Technologies",
//     "salary": "₹2,000,000 - ₹3,500,000",
//     "applyBy": "2026-03-19",
//     "skillRequired": ["Spark", "Kafka", "AWS Glue", "Data Warehousing", "Python"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-24"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef81",
//     "jobCategory": "Marketing",
//     "jobDesignation": "SEO Manager",
//     "jobLocation": "Remote",
//     "companyName": "SearchRank Pro",
//     "salary": "$70,000 - $90,000",
//     "applyBy": "2026-03-03",
//     "skillRequired": ["Technical SEO", "Content Strategy", "Team Leadership", "Analytics"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-12"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef82",
//     "jobCategory": "IT Operations",
//     "jobDesignation": "Database Administrator (DBA)",
//     "jobLocation": "Houston, TX",
//     "companyName": "DataGuard Systems",
//     "salary": "$80,000 - $100,000",
//     "applyBy": "2026-03-25",
//     "skillRequired": ["SQL Server", "Oracle", "Database Tuning", "Backup & Recovery"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-11"
//   },
//   {
//     "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef83",
//     "jobCategory": "Finance",
//     "jobDesignation": "Controller",
//     "jobLocation": "Boston, MA",
//     "companyName": "Growth Ventures LLC",
//     "salary": "$120,000 - $160,000",
//     "applyBy": "2026-03-18",
//     "skillRequired": ["Financial Reporting", "Budgeting", "Internal Controls", "CPA"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-09"
//   },
//   {
//     "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef84",
//     "jobCategory": "Healthcare",
//     "jobDesignation": "Clinical Research Coordinator",
//     "jobLocation": "Philadelphia, PA",
//     "companyName": "Pharma Innovations",
//     "salary": "$60,000 - $75,000",
//     "applyBy": "2026-04-02",
//     "skillRequired": ["Clinical Trials", "GCP", "Data Collection", "Patient Recruitment"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-04"
//   },
//   {
//     "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef85",
//     "jobCategory": "Education",
//     "jobDesignation": "School Counselor",
//     "jobLocation": "Denver, CO",
//     "companyName": "Community School District",
//     "salary": "$50,000 - $65,000",
//     "applyBy": "2026-04-15",
//     "skillRequired": ["Student Support", "Crisis Intervention", "College & Career Planning"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-06"
//   },
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef86",
//     "jobCategory": "Customer Service",
//     "jobDesignation": "Help Desk Technician",
//     "jobLocation": "Remote",
//     "companyName": "IT Support Pros",
//     "salary": "$40,000 - $55,000",
//     "applyBy": "2026-03-01",
//     "skillRequired": ["Technical Troubleshooting", "Windows OS", "Microsoft Office", "Ticketing Systems"],
//     "numberOfOpening": 5,
//     "jobPosted": "2026-01-10"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef87",
//     "jobCategory": "Software Development",
//     "jobDesignation": "Frontend Architect",
//     "jobLocation": "San Jose, CA",
//     "companyName": "UI/UX Innovations",
//     "salary": "$140,000 - $180,000",
//     "applyBy": "2026-03-27",
//     "skillRequired": ["React", "Angular", "Vue.js", "Frontend Architecture", "Performance Optimization"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-22"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef88",
//     "jobCategory": "Data Science",
//     "jobDesignation": "Data Governance Specialist",
//     "jobLocation": "Toronto, Canada",
//     "companyName": "DataTrust Solutions",
//     "salary": "CAD 80,000 - CAD 100,000",
//     "applyBy": "2026-03-13",
//     "skillRequired": ["Data Quality", "Data Privacy", "Compliance", "SQL"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-20"
//   },
//   {
//     "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef89",
//     "jobCategory": "Marketing",
//     "jobDesignation": "Content Writer",
//     "jobLocation": "Remote",
//     "companyName": "WordCraft Content",
//     "salary": "$45,000 - $60,000",
//     "applyBy": "2026-03-06",
//     "skillRequired": ["Copywriting", "SEO Writing", "Blog Posts", "Research"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-15"
//   },
//   {
//     "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef90",
//     "jobCategory": "Human Resources",
//     "jobDesignation": "HR Manager",
//     "jobLocation": "Sydney, Australia",
//     "companyName": "People & Culture Co.",
//     "salary": "AUD 90,000 - AUD 110,000",
//     "applyBy": "2026-03-30",
//     "skillRequired": ["HR Strategy", "Team Leadership", "Employee Relations", "Australian Employment Law"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-19"
//   },
//   {
//     "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef91",
//     "jobCategory": "Design",
//     "jobDesignation": "Senior UX Researcher",
//     "jobLocation": "San Francisco, CA",
//     "companyName": "User Insights Lab",
//     "salary": "$110,000 - $140,000",
//     "applyBy": "2026-03-16",
//     "skillRequired": ["User Interviews", "Usability Testing", "Survey Design", "Qualitative Research"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-02-04"
//   },
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef92",
//     "jobCategory": "Sales",
//     "jobDesignation": "Channel Sales Manager",
//     "jobLocation": "Remote",
//     "companyName": "Partner Growth Network",
//     "salary": "$95,000 - $125,000 + Commission",
//     "applyBy": "2026-03-10",
//     "skillRequired": ["Channel Partnerships", "Reseller Management", "Sales Enablement"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-18"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef93",
//     "jobCategory": "Software Development",
//     "jobDesignation": "Technical Lead (Java)",
//     "jobLocation": "Hyderabad, India",
//     "companyName": "Enterprise Solutions India",
//     "salary": "₹1,800,000 - ₹2,800,000",
//     "applyBy": "2026-03-29",
//     "skillRequired": ["Java", "Spring Boot", "Microservices", "System Design", "Team Leadership"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-23"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef94",
//     "jobCategory": "Data Science",
//     "jobDesignation": "Machine Learning Engineer (NLP)",
//     "jobLocation": "Remote",
//     "companyName": "Language AI Corp.",
//     "salary": "$120,000 - $160,000",
//     "applyBy": "2026-03-22",
//     "skillRequired": ["NLP", "Python", "Transformers", "Deep Learning", "Text Mining"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-27"
//   },
//   {
//     "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef95",
//     "jobCategory": "Marketing",
//     "jobDesignation": "Product Marketing Specialist",
//     "jobLocation": "Austin, TX",
//     "companyName": "Innovate Products Inc.",
//     "salary": "$75,000 - $95,000",
//     "applyBy": "2026-03-09",
//     "skillRequired": ["Product Launch", "Market Analysis", "Content Creation", "Sales Enablement"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-18"
//   },
//   {
//     "id": "b2c3d4e5-f6a7-8901-2345-67890abcdef96",
//     "jobCategory": "IT Operations",
//     "jobDesignation": "IT Support Manager",
//     "jobLocation": "New York, NY",
//     "companyName": "Global IT Services",
//     "salary": "$90,000 - $110,000",
//     "applyBy": "2026-03-28",
//     "skillRequired": ["Team Leadership", "ITIL", "Service Desk Management", "Vendor Management"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-17"
//   },
//   {
//     "id": "c3d4e5f6-a7b8-9012-3456-7890abcdef97",
//     "jobCategory": "Finance",
//     "jobDesignation": "Senior Accountant",
//     "jobLocation": "Chicago, IL",
//     "companyName": "Midwest Financial Group",
//     "salary": "$70,000 - $90,000",
//     "applyBy": "2026-03-20",
//     "skillRequired": ["General Ledger", "Month-End Close", "Financial Statements", "ERP Systems"],
//     "numberOfOpening": 1,
//     "jobPosted": "2026-01-10"
//   },
//   {
//     "id": "d4e5f6a7-b8c9-0123-4567-890abcdef98",
//     "jobCategory": "Healthcare",
//     "jobDesignation": "Nurse Practitioner",
//     "jobLocation": "Los Angeles, CA",
//     "companyName": "Wellness Clinic Network",
//     "salary": "$100,000 - $130,000",
//     "applyBy": "2026-04-05",
//     "skillRequired": ["Patient Assessment", "Diagnosis", "Prescribing Medication", "Advanced Practice Nursing"],
//     "numberOfOpening": 3,
//     "jobPosted": "2026-01-08"
//   },
//   {
//     "id": "e5f6a7b8-c9d0-1234-5678-90abcdef99",
//     "jobCategory": "Education",
//     "jobDesignation": "Admissions Counselor",
//     "jobLocation": "Remote",
//     "companyName": "Online University Pathways",
//     "salary": "$45,000 - $60,000",
//     "applyBy": "2026-03-10",
//     "skillRequired": ["Student Recruitment", "Admissions Process", "CRM", "Communication"],
//     "numberOfOpening": 2,
//     "jobPosted": "2026-01-07"
//   },
//   {
//     "id": "f6a7b8c9-d0e1-2345-6789-0abcdef100",
//     "jobCategory": "Customer Service",
//     "jobDesignation": "Client Relations Specialist",
//     "jobLocation": "London, UK",
//     "companyName": "Premium Services Group",
//     "salary": "£35,000 - £45,000",
//     "applyBy": "2026-03-05",
//     "skillRequired": ["Client Communication", "Issue Resolution", "CRM", "Relationship Building"],
//     "numberOfOpening": 3,
//     "jobPosted": "2026-01-13"
//   }
